name: Tests

on: [push]

jobs:
  build-contracts:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use node:16
        uses: actions/setup-node@v1
        with:
          node-version: "16.17.0"
      - name: Install dependencies
        run: yarn
      - name: Compile contracts
        run: yarn contracts compile
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
      - name: Build contracts
        run: yarn contracts build
        env:
          RPC_URL: ${{ secrets.RPC_URL }}

  build-webapp:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use node:16
        uses: actions/setup-node@v1
        with:
          node-version: "16.17.0"
      - name: Install dependencies
        run: yarn
      - name: Build contracts
        run: yarn contracts build
      - name: Build webapp
        run: yarn webapp build
